"""Contains constants for the current version of the TAS program."""

TAS_VERSION_MAJOR = 0
TAS_VERSION_MINOR = 0
TAS_VERSION_PATCH = 3

TAS_VERSION_STRING = f"{TAS_VERSION_MAJOR}.{TAS_VERSION_MINOR}.{TAS_VERSION_PATCH}"
