[tool.ruff]
target-version = "py312"
line-length = 100
select = [
  # https://beta.ruff.rs/docs/rules/
  "A",        # flake8-builtins
  "ANN",      # flake8-annotations
  "ARG",      # flake8-unused-arguments
  "B",        # bugbear
  "D",        # pydocstyle
  "E",        # pycodestyle
  # "ERA",    # eradicate (removes commented out code) - wait for code changes to calm down
  "F",        # pyflakes
  "FURB",     # refurb - blocks pre-commit cause fully in preview
  "I",        # isort
  "PL",       # pylint
  "RET",      # flake8-return
  "RUF100",   # Remove unused noqas
  "SIM",      # flake8-simplify
  "T20",      # flake8-print (no print statements)
  "TD",       # flake8-todos
  "TRY302",   # tryceratops useless-try-except
  "TRY401",   # tryceratops verbose-log-message
  "UP",       # pyupgrade
]
ignore = [
  "ANN002",   # Missing type annotation for *{name} (args)
  "ANN003",   # Missing type annotation for **{name} (kwargs)
  "ARG002",   # unused-method-argument - false positives on overrides
  "D104",     # undocumented-public-package
  "D203",     # one-blank-line-before-class
  "D212",     # multi-line-summary-first-line
  "PLR0911",  # too-many-return-statements
  "PLR0912",  # too-many-branches
  "PLR0913",  # too-many-arguments
  "PLR0915",  # too-many-statements
  "PLW0603",  # global-statement
  "TD003",    # missing-todo-link

  # slowly introducing those:                     % of warnings:
  "D102",     # undocumented-public-method        (~38%)
  "D101",     # undocumented-public-class         (~21%)
  "D107",     # undocumented-public-init          (~16%)
  "D105",     # undocumented-magic-method         (~12%)
  "D100",     # undocumented-public-module        (~ 9%)
  "D103",     # undocumented-public-function      (~ 3%)
  "D106",     # undocumented-public-nested-class  (~.4%)
]
unfixable = [
  "ERA",      # false positives
]

[tool.ruff.flake8-builtins]
builtins-ignorelist = [
  "format",
]

[tool.ruff.isort]
combine-as-imports = true