[tool.ruff]
target-version = "py312"
line-length = 100
select = [
  # https://beta.ruff.rs/docs/rules/
  "A",        # flake8-builtins
  "ANN",      # flake8-annotations
  "ARG",      # flake8-unused-arguments
  "B",        # bugbear
  "D200",     # pydocstyle fits-on-one-line
  "E",        # pycodestyle
  # "ERA",    # eradicate (removes commented out code) - wait for code changes to calm down
  "F",        # pyflakes
  "FURB",     # refurb
  "I",        # isort
  "PL",       # pylint
  "RET",      # flake8-return
  "SIM",      # flake8-simplify
  "T20",      # flake8-print (no print statements)
  "TD",       # flake8-todos
  "TRY302",   # tryceratops useless-try-except
  "TRY401",   # tryceratops verbose-log-message
  "UP",       # pyupgrade
]
ignore = [
  "ANN002",   # Missing type annotation for *{name} (args)
  "ANN003",   # Missing type annotation for **{name} (kwargs)
  "ARG002",   # unused-method-argument - false positives on overrides
  "PLR0911",  # too-many-return-statements
  "PLR0912",  # too-many-branches
  "PLR0913",  # too-many-arguments
  "PLR0915",  # too-many-statements
  "PLW0603",  # global-statement
  "TD003",    # missing-todo-link
]
unfixable = [
  "ERA",      # false positives
]

[tool.ruff.flake8-builtins]
builtins-ignorelist = [
  "format",
]

[tool.ruff.isort]
combine-as-imports = true